config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/", to: "welcome#index"

  get "/stations", to: "stations#index"
  get "/stations/:id", to: "stations#show"

  get "/trains", to: "trains#index"
  get "/trains/:id", to: "trains#show"

  get "/stations/:station_id/trains", to: "station_trains#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :trains
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :station
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/station_controller.rb
class StationController < ApplicationController
  def index
    # [ ] done

    # User Story 1, Parent Index 
    
    # For each parent table
    # As a visitor
    # When I visit '/parents'
    # Then I see the name of each parent record in the system
  end
end

app/controllers/station_trains_controller.rb
class StationTrainsController < ApplicationController
  def index
    @station = Station.find(params[:station_id])
    @trains = @station.trains
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all.order(created_at: :desc)
  end
  
  def show
    @station = Station.find(params[:id])
  end
  
end

# removed for I1,US6 - @stations = Station.all

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
    @trains = Train.all
  end

  def show
    @train = Train.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalTrainStations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Train Index", trains_path %>
    <%= link_to "Station Index", stations_path %>

    <%= yield %>
  </body>
</html>

app/views/station_trains/index.html.erb
<h1>Trains at <%= @station.name %></h1>

<% @trains.each do |train| %>
  <p>
    id#: <%= train.id %><br>
    Train Type: <%= train.train_type %><br>
    Capacity: <%= train.capacity %><br>
    Express?: <%= train.is_express ? 'Yes' : 'No' %>
  </p>
<% end %>

app/views/stations/index.html.erb
<h1>All Stations!</h1>

<% @stations.each do |station| %>
  <p>
    <%= station.name %>
    <br>
    Date Built: <%= station.created_at %>
  </p>
<% end %>

app/views/stations/show.html.erb
<%= link_to "Station_Trains Index", href: "station_trains#index" %>
<h1><%= @station.name %></h1>

<p>
  Platform Count: <%= @station.platform_count %><br>
  Food Stand?: <%= @station.food_stand ? "Yes" : "No" %><br>
  <br>
  Trains Available: <%= @station.trains.count %>
</p>

app/views/trains/index.html.erb
<h1>Trains!</h1>

<% @trains.each do |train| %>
  <p>
    Train Type: <%= train.train_type %><br>
    Capacity: <%= train.capacity %><br>
    Express?: <%= train.is_express ? "Yes" : "No" %>
  </p>
<% end %>

app/views/trains/show.html.erb
<h1>id#<%= @train.id %></h1>

<p>
  Train Type: <%= @train.train_type %><br>
  Capacity: <%= @train.capacity %><br>
  Is Express?: <%= @train.is_express ? "Yes" : "No" %>
</p>

app/views/welcome/index.html.erb
<h1>All Aboard!</h1>

<ul>
  <li><a href="/stations">I1,US1,Parent Index</a></li>
  <li><a href="/stations/1">I1,US2,Parent Show</a></li>
  <li><a href="/trains">I1,US3,Child Index</a></li>
  <li><a href="/trains/1">I1,US4,Child Show</a></li>
  <li><a href="/stations/2/trains">I1,US5,Parent Children Index</a></li>
  <li><a href="/stations">I1,US6,Parent Index sorted by Most Recently Created</a></li>
</ul>